name: Run Python Script

on:
  workflow_dispatch

env:
  client_id: ${{ secrets.CLIENT_ID }}
  client_secret: ${{ secrets.CLIENT_SECRET }}
  refresh_token: ${{secrets.REFRESH_TOKEN }}
  
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run Python Script
        run: |
          pip install requests
          python get_activities.py
      
  
  
  
